/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'slawomirandrian' at '8/5/16 3:23 PM' with Gradle 2.14
 *
 * @author slawomirandrian, @date 8/5/16 3:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
